<?php
$pageTitle='Escaner de inventario'; $pageEyebrow='Inventario / Conteo fisico'; $activeModule='inventario'; $activePage='escaner';
$pageAction='<span class="badge badge-soft-success fs-13 px-3 py-2"><span class="d-inline-block bg-success rounded-circle me-2" style="width:8px;height:8px"></span>Sesion activa: Conteo agosto</span>';
$pageScripts=<<<'HTML'
<script>
(function(){
 const input=document.getElementById('barcodeInput'), body=document.getElementById('scanRows'), count=document.getElementById('scanCount'), feedback=document.getElementById('scanFeedback');
 document.getElementById('scanForm').addEventListener('submit',function(e){
   e.preventDefault(); const code=input.value.trim(); if(!code) return;
   const now=new Date().toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'});
   const row=document.createElement('tr'); row.innerHTML='<td class="ps-3"><span class="font-monospace fw-semibold"></span></td><td><span class="fw-medium">Producto capturado manualmente</span><small class="d-block text-muted">Pendiente de validar en catalogo</small></td><td>Almacen principal</td><td>'+now+'</td><td><span class="badge badge-soft-info">Nuevo</span></td><td class="text-end pe-3"><button class="btn btn-sm btn-soft-danger" type="button"><i data-lucide="x" class="fs-16"></i></button></td>';
   row.querySelector('span').textContent=code; body.prepend(row); count.textContent=Number(count.textContent)+1; input.value=''; input.focus(); feedback.classList.remove('d-none'); setTimeout(()=>feedback.classList.add('d-none'),2200); if(window.lucide) lucide.createIcons();
 });
 body.addEventListener('click',function(e){const btn=e.target.closest('button');if(btn){btn.closest('tr').remove();count.textContent=Math.max(0,Number(count.textContent)-1);}});
})();
</script>
HTML;
require 'templates/page-start.php';
?>
<div class="row g-3 mb-4">
 <div class="col-lg-7"><div class="card h-100"><div class="card-body"><div class="d-flex justify-content-between align-items-start mb-3"><div><h5 class="card-title mb-1">Capturar codigo</h5><p class="text-muted mb-0">Usa un lector USB o escribe el codigo de barras.</p></div><span class="erp-kpi-icon bg-primary-subtle text-primary"><i data-lucide="scan-barcode"></i></span></div><div class="erp-scanner rounded d-flex flex-column align-items-center justify-content-center p-4"><div class="erp-scan-frame d-flex align-items-center justify-content-center mb-4"><i data-lucide="barcode" class="text-muted" style="width:120px;height:70px"></i></div><form id="scanForm" class="w-100" style="max-width:500px"><label for="barcodeInput" class="form-label fw-medium">Codigo de barras o SKU</label><div class="input-group input-group-lg"><span class="input-group-text"><i data-lucide="scan-line"></i></span><input id="barcodeInput" class="form-control font-monospace" placeholder="Escanea o escribe aqui..." autocomplete="off" autofocus><button class="btn btn-primary" type="submit">Agregar</button></div></form><div id="scanFeedback" class="alert alert-success py-2 px-3 mt-3 mb-0 d-none"><i data-lucide="circle-check" class="fs-17 me-1"></i>Producto agregado al conteo.</div></div></div></div></div>
 <div class="col-lg-5"><div class="card h-100"><div class="card-body"><h5 class="card-title mb-4">Resumen de sesion</h5><div class="d-flex align-items-center justify-content-between p-3 bg-light rounded mb-3"><div><p class="text-muted mb-1">Productos escaneados</p><h3 id="scanCount" class="mb-0">4</h3></div><span class="erp-kpi-icon bg-primary-subtle text-primary"><i data-lucide="scan-barcode"></i></span></div><div class="row g-3 mb-4"><div class="col-6"><div class="border rounded p-3"><small class="text-muted d-block mb-1">Coincidencias</small><h5 class="text-success mb-0">3</h5></div></div><div class="col-6"><div class="border rounded p-3"><small class="text-muted d-block mb-1">Diferencias</small><h5 class="text-warning mb-0">1</h5></div></div></div><div class="mb-3"><div class="d-flex justify-content-between mb-2"><span class="text-muted">Avance del conteo</span><span class="fw-semibold">32%</span></div><div class="progress" style="height:8px"><div class="progress-bar" style="width:32%"></div></div><small class="text-muted d-block mt-2">398 de 1,248 productos revisados</small></div><div class="d-grid gap-2"><button class="btn btn-primary"><i data-lucide="save" class="fs-17 me-1"></i>Guardar avance</button><button class="btn btn-soft-secondary"><i data-lucide="pause" class="fs-17 me-1"></i>Pausar sesion</button></div></div></div></div>
</div>
<div class="card"><div class="card-body border-bottom d-flex flex-wrap align-items-center justify-content-between gap-2"><div><h5 class="card-title mb-1">Ultimas capturas</h5><p class="text-muted mb-0 fs-13">Los productos mas recientes aparecen primero.</p></div><button class="btn btn-sm btn-soft-secondary"><i data-lucide="download" class="fs-15 me-1"></i>Descargar conteo</button></div><div class="table-responsive"><table class="table table-hover text-nowrap mb-0 erp-table"><thead><tr><th class="ps-3">Codigo</th><th>Producto</th><th>Ubicacion</th><th>Hora</th><th>Resultado</th><th class="text-end pe-3">Accion</th></tr></thead><tbody id="scanRows"><tr><td class="ps-3 font-monospace fw-semibold">7501042108724</td><td><span class="fw-medium">Toner laser negro XL</span><small class="d-block text-muted">CON-00872</small></td><td>Principal · C-18</td><td>11:42</td><td><span class="badge badge-soft-warning">Diferencia +2</span></td><td class="text-end pe-3"><button class="btn btn-sm btn-soft-danger" type="button"><i data-lucide="x" class="fs-16"></i></button></td></tr><tr><td class="ps-3 font-monospace fw-semibold">7501042101978</td><td><span class="fw-medium">Kit de herramientas 108 piezas</span><small class="d-block text-muted">HER-00197</small></td><td>Principal · D-09</td><td>11:39</td><td><span class="badge badge-soft-success">Coincide</span></td><td class="text-end pe-3"><button class="btn btn-sm btn-soft-danger" type="button"><i data-lucide="x" class="fs-16"></i></button></td></tr><tr><td class="ps-3 font-monospace fw-semibold">7501042101428</td><td><span class="fw-medium">Monitor LED 24 pulgadas</span><small class="d-block text-muted">ELE-00142</small></td><td>Principal · A-12</td><td>11:35</td><td><span class="badge badge-soft-success">Coincide</span></td><td class="text-end pe-3"><button class="btn btn-sm btn-soft-danger" type="button"><i data-lucide="x" class="fs-16"></i></button></td></tr><tr><td class="ps-3 font-monospace fw-semibold">7501042103187</td><td><span class="fw-medium">Silla ergonomica ejecutiva</span><small class="d-block text-muted">OFI-00318</small></td><td>Principal · B-04</td><td>11:31</td><td><span class="badge badge-soft-success">Coincide</span></td><td class="text-end pe-3"><button class="btn btn-sm btn-soft-danger" type="button"><i data-lucide="x" class="fs-16"></i></button></td></tr></tbody></table></div></div>
<?php require 'templates/scripts.php'; ?>
